# Generated by Django 5.0.4 on 2024-04-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mpaarating',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
