# Generated by Django 5.0.4 on 2024-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpaarating',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
